### ISSUE TITLE
Typo in README title

### ISSUE THREAD

**Issue by webduno** [lifercode/studio-threed#2]
I noticed that the main title of the README has a typo. The title should be "ThreeD Studio" instead of " TrheeD Studio".

![Captura de pantalla 2023-06-30 221331](https://github.com/lifercode/studio-threed/assets/71507184/0dca6d92-90a3-4012-a0ad-bfe422cf576f)

**Comment by lifercode** [comment]
Closing because @3dunoabraham already fixed it
